api = "0.4"

[buildpack]
id = "heroku/clojure"
version = "0.0.87"
name = "Clojure"
homepage = "https://github.com/heroku/heroku-buildpack-clojure"
description = "Official Heroku buildpack for Clojure applications. It uses Leiningen for building."
keywords = ["clojure", "leiningen"]

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]

[metadata.shim]
tarball = "https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku/clojure-v87.tgz"
sha256 = "86710aaba11ece315caefaad15db57153374c69846ac451c890505a28032ae68"

[metadata.release]

[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-clojure-buildpack"
