version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "skip changelog"
  - package-ecosystem: "cargo"
    # TODO: Switch this back to "/" once this repo is using cargo workspaces.
    directory: "/buildpacks/jvm-function-invoker"
    schedule:
      interval: "daily"
    labels:
      - "skip changelog"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "skip changelog"
