[[artifacts]]
version = "1.8.0_265"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/1.8.0_265.tar.gz"
checksum = "sha256:7cafe7cc263ba63115fb801049efb9bfae762c46f252a451ba05734224cb42da"
metadata.distribution = "zulu"

[[artifacts]]
version = "1.8.0_272"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/1.8.0_272.tar.gz"
checksum = "sha256:4cdd552c6740eb1bd641c1ed3686bdc2d8c3ec3a77cbf5557673ab7fa91c4aa5"
metadata.distribution = "zulu"

[[artifacts]]
version = "1.8.0_275"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/1.8.0_275.tar.gz"
checksum = "sha256:e456962656055aca1f9fdd9e03913ade8408c77a3fe0acf76e242bb56a56617d"
metadata.distribution = "zulu"

[[artifacts]]
version = "1.8.0_282"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/1.8.0_282.tar.gz"
checksum = "sha256:0f17f811529032750cff1b59a866e13c8f86f36cdb0c8c24c2a15956c1672976"
metadata.distribution = "zulu"

[[artifacts]]
version = "1.8.0_292"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/1.8.0_292.tar.gz"
checksum = "sha256:2d65396eb74649227e12fc2b15a89e76d665e6f1e4211cbafe89517ae8b57ed8"
metadata.distribution = "zulu"

[[artifacts]]
version = "1.8.0_302"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/1.8.0_302.tar.gz"
checksum = "sha256:7142637f7732e9fc42cc65cd2e7de17bda8832d04b4c103bef5382059e816c9a"
metadata.distribution = "zulu"

[[artifacts]]
version = "1.8.0_312"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/1.8.0_312.tar.gz"
checksum = "sha256:c8ff2193b1c132a00423835d7275006d867bfb66974c6ad948b82b36d2ca5d74"
metadata.distribution = "zulu"

[[artifacts]]
version = "1.8.0_322"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/1.8.0_322.tar.gz"
checksum = "sha256:159fd0859faa07ff84760568163905a4be195a4ac2949a078909680e73223516"
metadata.distribution = "zulu"

[[artifacts]]
version = "1.8.0_332"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/1.8.0_332.tar.gz"
checksum = "sha256:d309ba0d222f48d399eba16c8d1f761a7324673e8b31db76f9dd0af9d7abfed7"
metadata.distribution = "zulu"

[[artifacts]]
version = "1.8.0_342"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/1.8.0_342.tar.gz"
checksum = "sha256:94dbc96059e376fa07387d4b6d76816ba2e35963cd6388ac8fb1d9c2b8765315"
metadata.distribution = "zulu"

[[artifacts]]
version = "1.8.0_345"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/1.8.0_345.tar.gz"
checksum = "sha256:79a7eba651cfe61e59a820ae16b827fc5f7279c9ab62d497ee7fc89c7370d430"
metadata.distribution = "zulu"

[[artifacts]]
version = "1.8.0_352"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/1.8.0_352.tar.gz"
checksum = "sha256:1c7fd35976b8ca51fc5acad9f8bba345c68ae4df136537a9021e1b0e34b74b7b"
metadata.distribution = "zulu"

[[artifacts]]
version = "1.8.0_362"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/1.8.0_362.tar.gz"
checksum = "sha256:1cc27f96dec316cbfd302bff40569bfb734520716f38461b652e435c5f5a4007"
metadata.distribution = "zulu"

[[artifacts]]
version = "1.8.0_372"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/1.8.0_372.tar.gz"
checksum = "sha256:6b1e023ffe3a5822ab4ec5f65c7b429f59177c121e2b2726292ae89013d03158"
metadata.distribution = "zulu"

[[artifacts]]
version = "1.8.0_382"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/1.8.0_382.tar.gz"
checksum = "sha256:fc58f581ca1a570a534e87865fefc069c9dc98f01f3c60e671ccddcdcbd563b6"
metadata.distribution = "zulu"

[[artifacts]]
version = "1.8.0_392"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/1.8.0_392.tar.gz"
checksum = "sha256:f58ed8e63832102bc0d80985d607121c8a3bd886a69cf57babcdd4b5b212a8cd"
metadata.distribution = "zulu"

[[artifacts]]
version = "1.8.0_402"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/1.8.0_402.tar.gz"
checksum = "sha256:1012864bb62561f2c88006866b0de1c4b230591574b591f6d2a142d02a84a0a4"
metadata.distribution = "zulu"

[[artifacts]]
version = "1.8.0_412"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/1.8.0_412.tar.gz"
checksum = "sha256:739a1707b8fe24798ae8793667263b2d283d61b7958a576808b38a34fbd79ef1"
metadata.distribution = "zulu"

[[artifacts]]
version = "1.8.0_412"
os = "linux"
arch = "arm64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/arm64/1.8.0_412.tar.gz"
checksum = "sha256:9189e22cdef4d80f74e4415c4ad82ac0669b8ca1a4afad1ba132e2035f29f53c"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.10"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.10.tar.gz"
checksum = "sha256:93f3c964acde282869fd476963aab6409c57bd0dcc499261bfd9246d82faf44c"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.11"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.11.tar.gz"
checksum = "sha256:00348b30b1c6c4000f90c9cfcba44e01f1700997d3b2f4399f3eeccd44fd5296"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.12"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.12.tar.gz"
checksum = "sha256:c5fff0dd8fba50926bf0da86a3a063bc810e943d3fedb617636cf30263ae325d"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.13"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.13.tar.gz"
checksum = "sha256:296bbf05bf17c093e708676ced12da8742d8f99ba75ed74c3b43dae6bbd1bdaf"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.14.1"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.14.1.tar.gz"
checksum = "sha256:272bd98209eb0b730664379df0473504e09e2a0071563a654a1d8d7f4b02c307"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.14"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.14.tar.gz"
checksum = "sha256:47f4b3531ae627c8c0c3f8dcaf6c83fbffee1f220573b0f198e5f5f9bb49b60c"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.15"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.15.tar.gz"
checksum = "sha256:1021a9f2b1777c1c79e9983e77848c2671d596126aa30bfabf95a6d3d8802f26"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.16.1"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.16.1.tar.gz"
checksum = "sha256:81ae61cd77e4f83c994e13b39f90a4fce71b71679f8082af3f3fa145e3c39b17"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.16"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.16.tar.gz"
checksum = "sha256:7b455ce7c0d88578d3cf83a92e987ff2363ea0df56d3e4307c61b72ece5923cd"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.17"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.17.tar.gz"
checksum = "sha256:61a7ef76a2f07c99fecfe97412203a721292fc1bb09d3dd5b8f0db993bb9b6b6"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.18"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.18.tar.gz"
checksum = "sha256:51b891435c8509b72d11824ca9cf1cb58c0842f916fd5889deae93c8739ee71d"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.19"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.19.tar.gz"
checksum = "sha256:54954e8469833800c775acfabfaad8baf6742b46b1970b03b49682fe82e41839"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.2"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.2.tar.gz"
checksum = "sha256:adb4c99591d8889f2e3db96e9a15568d07e37c3a4cbcc7f819af49b1a48f0858"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.20.1"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.20.1.tar.gz"
checksum = "sha256:b50189fa2ff44019848b1e8501e716c8c9c1a2a36a596db510841edc2cda3557"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.20"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.20.tar.gz"
checksum = "sha256:88444c4d059772ce83980c6945d38079d313b510b415485a903fd3faa5476071"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.21"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.21.tar.gz"
checksum = "sha256:fce5efe3327ffbc4a4e29286e363a0c3d01de47836615de69e0cb09637a46ac4"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.22"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.22.tar.gz"
checksum = "sha256:b8278982c689cab951ef4daf60a6690f0aef671bbd13ead4f467e2d27e8af034"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.23"
os = "linux"
arch = "arm64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/arm64/11.0.23.tar.gz"
checksum = "sha256:5b8b551785c4f23417c10feba5e0342af300f491cb7f4c62c7ed84fd37857960"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.23"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.23.tar.gz"
checksum = "sha256:7ab8f4ff3f1c675d8ca9a904f5d3657afcb59b6d852c4c1b2c5988a2854896cd"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.8"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.8.tar.gz"
checksum = "sha256:4ae041b4ac8f18c3e835eb889805cf1f1e059bac8a26ac97e698b20805f9abe6"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.9.1"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.9.1.tar.gz"
checksum = "sha256:5039690d573f9080f7f794bd28b1674b1d5670bb74c2196277bfe2c059a6d125"
metadata.distribution = "zulu"

[[artifacts]]
version = "11.0.9"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/11.0.9.tar.gz"
checksum = "sha256:e225a197de3cda9772d9554959be072175f90030f0606e9fc06b7df33fa10b23"
metadata.distribution = "zulu"

[[artifacts]]
version = "17.0.0"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/17.0.0.tar.gz"
checksum = "sha256:3ce57da10bd5e78969b56fc0e1af96f5bb1acbafae66cfb1e6ec064fe309289a"
metadata.distribution = "zulu"

[[artifacts]]
version = "17.0.1"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/17.0.1.tar.gz"
checksum = "sha256:4161907c707830d6aec5d30df1cefbe5299bf9b4d102c06972b69ab16d3dc9a3"
metadata.distribution = "zulu"

[[artifacts]]
version = "17.0.10"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/17.0.10.tar.gz"
checksum = "sha256:f7917715465cbea766ffaf32cc0958eb0b1776ef9a89406800476d5c14a7931d"
metadata.distribution = "zulu"

[[artifacts]]
version = "17.0.11"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/17.0.11.tar.gz"
checksum = "sha256:474a59b57d194cf1e1189f51f14325b3be46001cf41b4246cee68a7cef29ddeb"
metadata.distribution = "zulu"

[[artifacts]]
version = "17.0.11"
os = "linux"
arch = "arm64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/arm64/17.0.11.tar.gz"
checksum = "sha256:e406854386e38f35a9529a14d1262f9db082afa3bef331f755943922c2f0f091"
metadata.distribution = "zulu"

[[artifacts]]
version = "17.0.2"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/17.0.2.tar.gz"
checksum = "sha256:d20c5856f27c541013c1cee07f6de5ef73eb2adf33559dc0f860dbf45a4431d0"
metadata.distribution = "zulu"

[[artifacts]]
version = "17.0.3"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/17.0.3.tar.gz"
checksum = "sha256:06d8b8e06825ff3282fa90db6bdb37f8c71663a4ac76f92cf17831e5e4e0d1e5"
metadata.distribution = "zulu"

[[artifacts]]
version = "17.0.4.1"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/17.0.4.1.tar.gz"
checksum = "sha256:5bd0116374e5b5f58debfc7d98e6d3e99e8738cb44ca822ae086bcc307ed8703"
metadata.distribution = "zulu"

[[artifacts]]
version = "17.0.4"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/17.0.4.tar.gz"
checksum = "sha256:a1547e86d37a07d175c1766b425c60fb348c3029c56942e828aa3acfe255ec23"
metadata.distribution = "zulu"

[[artifacts]]
version = "17.0.5"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/17.0.5.tar.gz"
checksum = "sha256:996a6723607471112d490220da39477266fabe89085c0de8401beee62fb5e222"
metadata.distribution = "zulu"

[[artifacts]]
version = "17.0.6"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/17.0.6.tar.gz"
checksum = "sha256:197b8f6c5041008a9b83605182dbaa431664ad4238f075c1f891453b8d3f3794"
metadata.distribution = "zulu"

[[artifacts]]
version = "17.0.7"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/17.0.7.tar.gz"
checksum = "sha256:afb2d54e764910e610cf9904844a5d13fd0df069ca4c171a9ef6e233092e4fe3"
metadata.distribution = "zulu"

[[artifacts]]
version = "17.0.8.1"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/17.0.8.1.tar.gz"
checksum = "sha256:54ea552c9b1deb4599d71cff08ea8ed04fe172cf55cbd9fafa6025173c10a6c4"
metadata.distribution = "zulu"

[[artifacts]]
version = "17.0.8"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/17.0.8.tar.gz"
checksum = "sha256:76528807648e4c74bf27ff0f1defb1d2d450c27c5f081c199608ac1273d55be0"
metadata.distribution = "zulu"

[[artifacts]]
version = "17.0.9"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/17.0.9.tar.gz"
checksum = "sha256:86e5bb1d034d3ba81faead309bf2edc7fc462488b5bed3f9f3ec0a936fedfb6a"
metadata.distribution = "zulu"

[[artifacts]]
version = "21.0.0"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/21.0.0.tar.gz"
checksum = "sha256:571cc47dc3c976a8b820bd652f2084face30ac6ce73c2b0159a4ba1ab462da38"
metadata.distribution = "zulu"

[[artifacts]]
version = "21.0.1"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/21.0.1.tar.gz"
checksum = "sha256:76296ebce7edc3d796d4eb83b87ed99eb6ea0c3d8041419b96c18fba28d011dd"
metadata.distribution = "zulu"

[[artifacts]]
version = "21.0.2"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/21.0.2.tar.gz"
checksum = "sha256:8b3c6bb9dab4608dd3a464d75342747e8eec9fc80b2aab459f92f6d3a6bb32fb"
metadata.distribution = "zulu"

[[artifacts]]
version = "21.0.3"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/21.0.3.tar.gz"
checksum = "sha256:057674a3aff2110a5e11187ecb57ed1342efa89fab63587b20cd3785e374b9b8"
metadata.distribution = "zulu"

[[artifacts]]
version = "21.0.3"
os = "linux"
arch = "arm64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/arm64/21.0.3.tar.gz"
checksum = "sha256:02968e30fb3037a89e89a9d4e56e39918db8e5118893e42bf4c880e9779027dc"
metadata.distribution = "zulu"


[[artifacts]]
version = "22.0.0"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/22.0.0.tar.gz"
checksum = "sha256:3e88ed145f0dfdf693ac93ffc9f6763dfaad09445ee150d61b0174cb05bd9d82"
metadata.distribution = "zulu"

[[artifacts]]
version = "22.0.1"
os = "linux"
arch = "amd64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/amd64/22.0.1.tar.gz"
checksum = "sha256:44a1a5883f1c67a59e5dafcef0538c09e09ac849dfb24e1088f9529080c1fd43"
metadata.distribution = "zulu"

[[artifacts]]
version = "22.0.1"
os = "linux"
arch = "arm64"
url = "https://heroku-buildpacks-jvm.s3.us-east-1.amazonaws.com/openjdk/zulu/arm64/22.0.1.tar.gz"
checksum = "sha256:263f1773515a42d1ae85a4c911530f4af6e4dabe466a386a9698e922c94e950f"
metadata.distribution = "zulu"
