[package]
name = "buildpack-heroku-add-cnb-require-jdk"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
libcnb.workspace = true
