[package]
name = "buildpacks-jvm-shared"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
indoc = "2.0.1"
libherokubuildpack.workspace = true
libcnb.workspace = true
