api = "0.9"

[buildpack]
id = "heroku/sbt"
version = "4.0.1"
name = "Heroku sbt"
homepage = "https://github.com/heroku/buildpacks-jvm"
description = "Heroku's sbt buildpack. A component of the 'heroku/scala' buildpack."
keywords = ["sbt", "heroku"]
clear-env = true

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[stacks]]
id = "*"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-sbt" }
