api = "0.10"

[buildpack]
id = "heroku/sbt"
version = "7.0.2"
name = "Heroku sbt"
homepage = "https://github.com/heroku/buildpacks-jvm"
description = "Heroku's sbt buildpack. A component of the 'heroku/scala' buildpack."
keywords = ["sbt", "heroku"]
clear-env = true

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-sbt" }
