api = "0.9"

[buildpack]
id = "heroku/sbt"
version = "3.1.0"
name = "sbt"
clear-env = true
homepage = "https://github.com/heroku/buildpacks-jvm"
description = "Official Heroku buildpack for sbt applications."
keywords = ["java", "scala", "sbt"]

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[stacks]]
id = "*"

[metadata]
[metadata.release]
[metadata.release.image]
repository = "docker.io/heroku/buildpack-sbt"
