api = "0.9"

[buildpack]
id = "heroku/scala"
version = "4.1.1"
name = "Heroku Scala"
homepage = "https://github.com/heroku/buildpacks-jvm"
description = "Heroku's buildpack for Scala applications."
keywords = ["scala", "openjdk", "sbt", "heroku"]

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[order]]

[[order.group]]
id = "heroku/jvm"
version = "4.1.1"

[[order.group]]
id = "heroku/sbt"
version = "4.1.1"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-scala" }
