api = "0.9"

[buildpack]
id = "heroku/scala"
version = "1.1.2"
name = "Scala"
homepage = "https://github.com/heroku/buildpacks-jvm"
description = "Official Heroku buildpack for Scala applications."
keywords = ["scala"]

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[order]]

[[order.group]]
id = "heroku/jvm"
version = "1.1.2"

[[order.group]]
id = "heroku/sbt"
version = "1.1.2"

[[order.group]]
id = "heroku/procfile"
version = "2.0.0"
optional = true

[metadata]
[metadata.release]
[metadata.release.docker]
repository = "docker.io/heroku/buildpack-scala"
