api = "0.8"

[buildpack]
id = "heroku/scala"
version = "0.0.1"
name = "Scala"
homepage = "https://github.com/heroku/buildpacks-jvm"
description = "Official Heroku buildpack for Scala applications."
keywords = ["scala", "java"]

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[order]]

[[order.group]]
id = "heroku/jvm"
version = "1.0.6"

[[order.group]]
id = "heroku/sbt"
version = "0.0.1"

[[order.group]]
id = "heroku/procfile"
version = "2.0.0"
optional = true

[metadata]
[metadata.release]
[metadata.release.docker]
repository = "public.ecr.aws/heroku-buildpacks/heroku-scala-buildpack"
