api = "0.10"

[buildpack]
id = "heroku/scala"
version = "7.0.4"
name = "Heroku Scala"
homepage = "https://github.com/heroku/buildpacks-jvm"
description = "Heroku's buildpack for Scala applications."
keywords = ["scala", "openjdk", "sbt", "heroku"]

[[buildpack.licenses]]
type = "BSD-3-Clause"

[[order]]

[[order.group]]
id = "heroku/jvm"
version = "7.0.4"

[[order.group]]
id = "heroku/sbt"
version = "7.0.4"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-scala" }

# Targets for this buildpack, used by languages-github-actions when releasing.
# Can be removed as soon as pack supports packaging composite multi-arch buildpacks.
[[metadata.targets]]
os = "linux"
arch = "amd64"

[[metadata.targets]]
os = "linux"
arch = "arm64"
