name: Release Buildpacks

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  detect:
    name: Detecting Buildpacks
    uses: heroku/languages-github-actions/.github/workflows/_buildpacks-release-detect.yml@main

  package:
    name: ${{ matrix.id }}
    needs: [ detect ]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.detect.outputs.buildpacks) }}
    uses: heroku/languages-github-actions/.github/workflows/_buildpacks-release-package.yml@main
    with:
      buildpack_id: ${{ matrix.id }}
      buildpack_path: ${{ matrix.path }}

  publish-docker:
    name: ${{ matrix.id }}
    needs: [ detect, package ]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.detect.outputs.buildpacks) }}
    uses: heroku/languages-github-actions/.github/workflows/_buildpacks-release-publish-docker.yml@main
    with:
      buildpack_id: ${{ matrix.id }}
    secrets:
      docker_hub_user: ${{ secrets.DOCKER_HUB_USER }}
      docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}

  publish-github:
    name: ${{ matrix.id }}
    needs: [ detect, package ]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.detect.outputs.buildpacks) }}
    uses: heroku/languages-github-actions/.github/workflows/_buildpacks-release-publish-github.yml@main
    with:
      buildpack_id: ${{ matrix.id }}

  publish-cnb:
    name: ${{ matrix.id }}
    needs: [ detect, publish-docker ]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.detect.outputs.buildpacks) }}
    uses: heroku/languages-github-actions/.github/workflows/_buildpacks-release-publish-cnb-registry.yml@main
    with:
      buildpack_id: ${{ matrix.id }}
    secrets:
      cnb_registry_token: ${{ secrets.CNB_REGISTRY_RELEASE_BOT_GITHUB_TOKEN }}

  update-builder:
    name: ${{ matrix.id }}
    needs: [ detect, publish-docker, publish-cnb, publish-github ]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.detect.outputs.buildpacks) }}
    uses: heroku/languages-github-actions/.github/workflows/_buildpacks-release-update-builder.yml@main
    with:
      buildpack_id: ${{ matrix.id }}
      app_id: ${{ vars.LINGUIST_GH_APP_ID }}
    secrets:
      app_private_key: ${{ secrets.LINGUIST_GH_PRIVATE_KEY }}
